//! Known-answer interop tests against the Python LXMF reference (LXMF 1.0.1).
//!
//! Vector from `reference/lxmfref.py pack <src=05*32/06*32> <dst=07*32/08*32>
//! "Greetings" "Hello from Python LXMF" 1700000000.0`. The source identity's
//! public key is the fixed reference key. This locks our msgpack payload
//! encoding, message-id hashing and Ed25519 signature verification to the
//! reference byte-for-byte. The Rust->Python direction is covered by
//! `scripts/interop.sh`.

use lxmf::message::{extract_ticket, parse};
use reticulum_core::identity::PublicIdentity;

fn unhex(s: &str) -> Vec<u8> {
    let s: String = s.chars().filter(|c| !c.is_whitespace()).collect();
    (0..s.len()).step_by(2).map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap()).collect()
}

#[test]
fn parses_and_verifies_python_lxmf_message() {
    let packed = unhex(
        "021e68345db8a80c29d0c2f193baa5f420f7e44b55b06cff39719106f2bd1fd2\
         cfeaf89e57248baad43791a115345482f6b54b6e90aa0d02b5d8eddad1dc6a6a\
         323ec74921c618ae95e69153e9645db6f223d5d387db37ae23f58ef1f0560700\
         94cb41d954fc40000000c4094772656574696e6773c41648656c6c6f2066726f\
         6d20507974686f6e204c584d4680",
    );
    // fixed reference source identity public key (x25519=05*32, ed25519=06*32)
    let src_pub = PublicIdentity::from_public_key(&unhex(
        "50a61409b1ddd0325e9b16b700e719e9772c07000b1bd7786e907c653d20495d\
         8a875fff1eb38451577acd5afee405456568dd7c89e090863a0557bc7af49f17",
    ))
    .unwrap();

    let m = parse(&packed, Some(&src_pub)).expect("parse python lxmf");
    assert!(m.signature_validated, "signature must verify against reference source key");
    assert_eq!(m.title_string(), "Greetings");
    assert_eq!(m.content_string(), "Hello from Python LXMF");
    assert_eq!(reticulum_core::hex(&m.source_hash), "20f7e44b55b06cff39719106f2bd1fd2");
    assert_eq!(reticulum_core::hex(&m.destination_hash), "021e68345db8a80c29d0c2f193baa5f4");
    assert_eq!(reticulum_core::hex(&m.message_id), "c00af1f9ba72e66d4b9a41fbe76a55d6bbb1c8dfb9271f0cf660ed101e174c96");
}

#[test]
fn extracts_ticket_from_python_lxmf_message() {
    // A real LXMF message carrying FIELD_TICKET (0x0C) = [expires, ticket(16)],
    // generated by the Python LXMF library (a "trusted" sender's message).
    let packed = unhex(
        "82b6ec8154dbd0f3f00fde271e0df97b34614d6807881c0d7862c7f59c958e68\
         553e24f9999ca75332a2ecbd099775355a6fcf5872a4225b0a237d072fbfe0ad\
         c57337c82327743a1691d3bc6aa64c9cb4c9b9b539ffe9f9d81d80e0bee0df0e\
         94cb41da89cc86a78eebc400c40e68692066726f6d20667269656e64810c92cb\
         41da90b866a78e4cc4101567685e8bcf7960e20135c218bc8492",
    );
    let src_pub = PublicIdentity::from_public_key(&unhex(
        "eeb8ca64cdb1801637b33bec34edc11fccf1e35e8ba4fe6b3e446f30f8eae91c\
         412daca1fbbf826e64d0fd5d16a1cca660161c8102857497f454c4a9f73227ae",
    ))
    .unwrap();

    let m = parse(&packed, Some(&src_pub)).expect("parse ticket message");
    assert!(m.signature_validated, "signature must verify (we only honour tickets from verified senders)");

    let t = extract_ticket(&m.fields).expect("FIELD_TICKET must be extracted");
    assert_eq!(reticulum_core::hex(&t.ticket), "1567685e8bcf7960e20135c218bc8492");
    assert_eq!(t.expires, 1782768026);
}
